env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  indent:
    - 0
  linebreak-style:
    - warn
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars:
    - 0
  no-mixed-spaces-and-tabs:
    - 0
  no-undef:
    - 0
